/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */

using System.Collections.Generic;

namespace kinetica
{
    /// @cond NO_DOCS
    public class AlterModelRequest : KineticaData
    {
        public struct Action
        {
            public const string CONTAINER = "container";
            public const string REGISTRY = "registry";
            public const string REFRESH = "refresh";
            public const string STOP_DEPLOYMENT = "stop_deployment";
        } // end struct Action

        public string model_name { get; set; }
        public string action { get; set; }
        public string _value { get; set; }
        public IDictionary<string, string> options { get; set; } = new Dictionary<string, string>();

        public AlterModelRequest() { }

        public AlterModelRequest( string model_name,
                                  string action,
                                  string _value,
                                  IDictionary<string, string> options = null)
        {
            this.model_name = model_name ?? "";
            this.action = action ?? "";
            this._value = _value ?? "";
            this.options = options ?? new Dictionary<string, string>();
        } // end constructor
    } // end class AlterModelRequest
    /// @endcond

    /// @cond NO_DOCS
    public class AlterModelResponse : KineticaData
    {
        public string model_name { get; set; }
        public string action { get; set; }
        public string _value { get; set; }
        public IDictionary<string, string> info { get; set; } = new Dictionary<string, string>();
    } // end class AlterModelResponse
    /// @endcond
} // end namespace kinetica
