/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */

using System.Collections.Generic;

namespace kinetica;

/// <summary>A set of parameters for <see
/// cref="Kinetica.dropBackup">Kinetica.dropBackup</see>.</summary>
/// <remarks><para>Deletes one or more existing database <a
/// href="../../../admin/backup_restore/#database-backup"
/// target="_top">backups</a> and contained snapshots, accessible via the <a
/// href="../../../concepts/data_sinks/" target="_top">data sink</a> specified
/// by <see cref="DropBackupRequest.datasink_name" />.</para></remarks>
public class DropBackupRequest : KineticaData
{
    /// <summary>A set of string constants for the parameter <see
    /// cref="DropBackupRequest.options" />.</summary>
    /// <remarks><para>Optional parameters.</para></remarks>
    public struct Options
    {
        /// <summary>Whether or not to perform a dry run of a backup deletion.
        /// </summary>
        /// <remarks><para>Supported values:</para>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see cref="DropBackupRequest.Options.TRUE">TRUE</see>
        ///         </term>
        ///     </item>
        ///     <item>
        ///         <term><see
        ///         cref="DropBackupRequest.Options.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// <para>The default value is <see
        /// cref="DropBackupRequest.Options.FALSE">FALSE</see>.</para>
        /// </remarks>
        public const string DRY_RUN = "dry_run";

        public const string TRUE = "true";
        public const string FALSE = "false";

        /// <summary>Allow multiple backups to be deleted if <see
        /// cref="DropBackupRequest.Options.TRUE">TRUE</see> and multiple
        /// backup names are found matching <see
        /// cref="DropBackupRequest.backup_name" />.</summary>
        /// <remarks><para>Supported values:</para>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see cref="DropBackupRequest.Options.TRUE">TRUE</see>
        ///         </term>
        ///     </item>
        ///     <item>
        ///         <term><see
        ///         cref="DropBackupRequest.Options.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// <para>The default value is <see
        /// cref="DropBackupRequest.Options.FALSE">FALSE</see>.</para>
        /// </remarks>
        public const string DELETE_ALL_BACKUPS = "delete_all_backups";

        /// <summary>Whether or not to suppress the error if the specified
        /// backup does not exist.</summary>
        /// <remarks><para>Supported values:</para>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see cref="DropBackupRequest.Options.TRUE">TRUE</see>
        ///         </term>
        ///     </item>
        ///     <item>
        ///         <term><see
        ///         cref="DropBackupRequest.Options.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// <para>The default value is <see
        /// cref="DropBackupRequest.Options.FALSE">FALSE</see>.</para>
        /// </remarks>
        public const string NO_ERROR_IF_NOT_EXISTS = "no_error_if_not_exists";
    } // end struct Options

    /// <summary>Name of the backup to be deleted.</summary>
    /// <remarks><para>An empty string or '*' will delete all existing backups.
    /// Any text followed by a '*' will delete backups whose name starts with
    /// that text.  When deleting multiple backups, <see
    /// cref="DropBackupRequest.Options.DELETE_ALL_BACKUPS">DELETE_ALL_BACKUPS</see>
    /// must be set to <see cref="DropBackupRequest.Options.TRUE">TRUE</see>.
    /// </para></remarks>
    public string backup_name { get; set; }

    /// <summary>Data sink through which the backup is accessible.</summary>
    public string datasink_name { get; set; }

    /// <summary>Optional parameters.</summary>
    /// <remarks><list type="bullet">
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.DRY_RUN">DRY_RUN</see>:</term>
    ///         <description>Whether or not to perform a dry run of a backup
    ///         deletion.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.DELETE_ALL_BACKUPS">DELETE_ALL_BACKUPS</see>:
    ///         </term>
    ///         <description>Allow multiple backups to be deleted if <see
    ///         cref="DropBackupRequest.Options.TRUE">TRUE</see> and multiple
    ///         backup names are found matching <see
    ///         cref="DropBackupRequest.backup_name" />.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.NO_ERROR_IF_NOT_EXISTS">NO_ERROR_IF_NOT_EXISTS</see>:
    ///         </term>
    ///         <description>Whether or not to suppress the error if the
    ///         specified backup does not exist.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    /// </list>
    /// <para>The default value is an empty Dictionary.</para></remarks>
    public IDictionary<string, string> options { get; set; } = new Dictionary<string, string>();

    /// <summary>Constructs a DropBackupRequest object with default parameters.
    /// </summary>
    public DropBackupRequest() { }

    /// <summary>Constructs a DropBackupRequest object with the specified
    /// parameters.</summary>
    ///
    /// <param name="backup_name">Name of the backup to be deleted. An empty
    /// string or '*' will delete all existing backups. Any text followed by a
    /// '*' will delete backups whose name starts with that text.  When
    /// deleting multiple backups, <see
    /// cref="DropBackupRequest.Options.DELETE_ALL_BACKUPS">DELETE_ALL_BACKUPS</see>
    /// must be set to <see cref="DropBackupRequest.Options.TRUE">TRUE</see>.
    /// </param>
    /// <param name="datasink_name">Data sink through which the backup is
    /// accessible.</param>
    /// <param name="options">Optional parameters.
    /// <list type="bullet">
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.DRY_RUN">DRY_RUN</see>:</term>
    ///         <description>Whether or not to perform a dry run of a backup
    ///         deletion.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.DELETE_ALL_BACKUPS">DELETE_ALL_BACKUPS</see>:
    ///         </term>
    ///         <description>Allow multiple backups to be deleted if <see
    ///         cref="DropBackupRequest.Options.TRUE">TRUE</see> and multiple
    ///         backup names are found matching <paramref name="backup_name"
    ///         />.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    ///     <item>
    ///         <term><see
    ///         cref="DropBackupRequest.Options.NO_ERROR_IF_NOT_EXISTS">NO_ERROR_IF_NOT_EXISTS</see>:
    ///         </term>
    ///         <description>Whether or not to suppress the error if the
    ///         specified backup does not exist.
    ///         Supported values:
    ///         <list type="bullet">
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.TRUE">TRUE</see></term>
    ///             </item>
    ///             <item>
    ///                 <term><see
    ///                 cref="DropBackupRequest.Options.FALSE">FALSE</see>
    ///                 </term>
    ///             </item>
    ///         </list>
    ///         The default value is <see
    ///         cref="DropBackupRequest.Options.FALSE">FALSE</see>.
    ///         </description>
    ///     </item>
    /// </list>
    /// The default value is an empty Dictionary.</param>
    public DropBackupRequest( string backup_name,
                              string datasink_name,
                              IDictionary<string, string> options = null)
    {
        this.backup_name = backup_name ?? "";
        this.datasink_name = datasink_name ?? "";
        this.options = options ?? new Dictionary<string, string>();
    } // end constructor
} // end class DropBackupRequest

/// <summary>A set of results returned by <see
/// cref="Kinetica.dropBackup">Kinetica.dropBackup</see>.</summary>
public class DropBackupResponse : KineticaData
{
    /// <summary>Value of <see
    /// cref="DropBackupRequest.backup_name">backup_name</see>.</summary>
    public string backup_name { get; set; }

    /// <summary>Names of backups that were deleted.</summary>
    public IList<string> backup_names { get; set; } = new List<string>();

    /// <summary>Additional information.</summary>
    public IDictionary<string, string> info { get; set; } = new Dictionary<string, string>();
} // end class DropBackupResponse
