/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */

using System.Collections.Generic;



namespace kinetica
{
    /// @cond NO_DOCS
    /// <summary>A set of parameters for <see
    /// cref="Kinetica.reserveResource(string,long,IDictionary{string, string})"
    /// />.
    /// <br />
    /// </summary>
    public class ReserveResourceRequest : KineticaData
    {

        /// <summary>
        /// <list type="bullet">
        /// </list>
        /// <br />
        /// A set of string constants for the parameter <see cref="options"
        /// />.</summary>
        public struct Options
        {
        } // end struct Options

        public string component { get; set; }
        public long bytes_requested { get; set; }

        /// <summary>
        /// <list type="bullet">
        /// </list>
        /// </summary>
        public IDictionary<string, string> options { get; set; } = new Dictionary<string, string>();


        /// <summary>Constructs a ReserveResourceRequest object with default
        /// parameters.</summary>
        public ReserveResourceRequest() { }

        /// <summary>Constructs a ReserveResourceRequest object with the
        /// specified parameters.</summary>
        /// 
        /// <param name="component"></param>
        /// <param name="bytes_requested"></param>
        /// <param name="options">
        /// <list type="bullet">
        /// </list>
        /// </param>
        /// 
        public ReserveResourceRequest( string component,
                                       long bytes_requested,
                                       IDictionary<string, string> options = null)
        {
            this.component = component ?? "";
            this.bytes_requested = bytes_requested;
            this.options = options ?? new Dictionary<string, string>();
        } // end constructor

    } // end class ReserveResourceRequest
    /// @endcond



    /// @cond NO_DOCS
    /// <summary>A set of results returned by <see
    /// cref="Kinetica.reserveResource(string,long,IDictionary{string, string})"
    /// />.</summary>
    public class ReserveResourceResponse : KineticaData
    {
        public string component { get; set; }
        public long reservation { get; set; }
        public IDictionary<string, string> info { get; set; } = new Dictionary<string, string>();

    } // end class ReserveResourceResponse
    /// @endcond





}  // end namespace kinetica
