/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */

using System.Collections.Generic;



namespace kinetica
{

    /// <summary>@private
    /// A set of parameters for <see
    /// cref="Kinetica.visualizeImageLabels(string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,double,double,double,double,int,int,string,IDictionary{string, string})"
    /// />.
    /// <br />
    /// </summary>
    public class VisualizeImageLabelsRequest : KineticaData
    {

        /// <summary>@private
        /// <br />
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.
        /// A set of string constants for the parameter <see cref="projection"
        /// />.</summary>
        public struct Projection
        {

            /// <summary>@private
            /// </summary>
            public const string EPSG_4326 = "EPSG:4326";

            /// <summary>@private
            /// </summary>
            public const string PLATE_CARREE = "PLATE_CARREE";

            /// <summary>@private
            /// </summary>
            public const string _900913 = "900913";

            /// <summary>@private
            /// </summary>
            public const string EPSG_900913 = "EPSG:900913";

            /// <summary>@private
            /// </summary>
            public const string _102100 = "102100";

            /// <summary>@private
            /// </summary>
            public const string EPSG_102100 = "EPSG:102100";

            /// <summary>@private
            /// </summary>
            public const string _3857 = "3857";

            /// <summary>@private
            /// </summary>
            public const string EPSG_3857 = "EPSG:3857";

            /// <summary>@private
            /// </summary>
            public const string WEB_MERCATOR = "WEB_MERCATOR";

    /// <summary>@private
    /// </summary>
        } // end struct Projection


        /// <summary>@private
        /// </summary>

        /// <summary>@private
        /// </summary>
        public string table_name { get; set; }

        /// <summary>@private
        /// </summary>
        public string x_column_name { get; set; }

        /// <summary>@private
        /// </summary>
        public string y_column_name { get; set; }

        /// <summary>@private
        /// </summary>
        public string x_offset { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string y_offset { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string text_string { get; set; }

        /// <summary>@private
        /// </summary>
        public string font { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string text_color { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string text_angle { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string text_scale { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string draw_box { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string draw_leader { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string line_width { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string line_color { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string fill_color { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string leader_x_column_name { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string leader_y_column_name { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public string filter { get; set; } = "";

        /// <summary>@private
        /// </summary>
        public double min_x { get; set; }

        /// <summary>@private
        /// </summary>
        public double max_x { get; set; }

        /// <summary>@private
        /// </summary>
        public double min_y { get; set; }

        /// <summary>@private
        /// </summary>
        public double max_y { get; set; }

        /// <summary>@private
        /// </summary>
        public int width { get; set; }

        /// <summary>@private
        /// </summary>
        public int height { get; set; }

        /// <summary>@private
        /// <br />
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.</summary>
        public string projection { get; set; } = Projection.PLATE_CARREE;

        /// <summary>@private
        /// </summary>
        public IDictionary<string, string> options { get; set; } = new Dictionary<string, string>();


        /// <summary>@private
        /// Constructs a VisualizeImageLabelsRequest object with default
        /// parameters.</summary>
        public VisualizeImageLabelsRequest() { }

        /// <summary>@private
        /// Constructs a VisualizeImageLabelsRequest object with the specified
        /// parameters.</summary>
        /// 
        /// <param name="table_name"></param>
        /// <param name="x_column_name"></param>
        /// <param name="y_column_name"></param>
        /// <param name="x_offset"></param>
        /// <param name="y_offset"></param>
        /// <param name="text_string"></param>
        /// <param name="font"></param>
        /// <param name="text_color"></param>
        /// <param name="text_angle"></param>
        /// <param name="text_scale"></param>
        /// <param name="draw_box"></param>
        /// <param name="draw_leader"></param>
        /// <param name="line_width"></param>
        /// <param name="line_color"></param>
        /// <param name="fill_color"></param>
        /// <param name="leader_x_column_name"></param>
        /// <param name="leader_y_column_name"></param>
        /// <param name="filter"></param>
        /// <param name="min_x"></param>
        /// <param name="max_x"></param>
        /// <param name="min_y"></param>
        /// <param name="max_y"></param>
        /// <param name="width"></param>
        /// <param name="height"></param>
        /// <param name="projection">
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageLabelsRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageLabelsRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.</param>
        /// <param name="options"></param>
        /// 
        public VisualizeImageLabelsRequest( string table_name,
                                            string x_column_name,
                                            string y_column_name,
                                            string x_offset,
                                            string y_offset,
                                            string text_string,
                                            string font,
                                            string text_color,
                                            string text_angle,
                                            string text_scale,
                                            string draw_box,
                                            string draw_leader,
                                            string line_width,
                                            string line_color,
                                            string fill_color,
                                            string leader_x_column_name,
                                            string leader_y_column_name,
                                            string filter,
                                            double min_x,
                                            double max_x,
                                            double min_y,
                                            double max_y,
                                            int width,
                                            int height,
                                            string projection = null,
                                            IDictionary<string, string> options = null)
        {
            this.table_name = table_name ?? "";
            this.x_column_name = x_column_name ?? "";
            this.y_column_name = y_column_name ?? "";
            this.x_offset = x_offset ?? "";
            this.y_offset = y_offset ?? "";
            this.text_string = text_string ?? "";
            this.font = font ?? "";
            this.text_color = text_color ?? "";
            this.text_angle = text_angle ?? "";
            this.text_scale = text_scale ?? "";
            this.draw_box = draw_box ?? "";
            this.draw_leader = draw_leader ?? "";
            this.line_width = line_width ?? "";
            this.line_color = line_color ?? "";
            this.fill_color = fill_color ?? "";
            this.leader_x_column_name = leader_x_column_name ?? "";
            this.leader_y_column_name = leader_y_column_name ?? "";
            this.filter = filter ?? "";
            this.min_x = min_x;
            this.max_x = max_x;
            this.min_y = min_y;
            this.max_y = max_y;
            this.width = width;
            this.height = height;
            this.projection = projection ?? Projection.PLATE_CARREE;
            this.options = options ?? new Dictionary<string, string>();
        } // end constructor


    /// <summary>@private
    /// </summary>
    } // end class VisualizeImageLabelsRequest



    /// <summary>@private
    /// A set of results returned by <see
    /// cref="Kinetica.visualizeImageLabels(string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,double,double,double,double,int,int,string,IDictionary{string, string})"
    /// />.</summary>
    public class VisualizeImageLabelsResponse : KineticaData
    {

        /// <summary>@private
        /// </summary>

        /// <summary>@private
        /// </summary>
        public double width { get; set; }

        /// <summary>@private
        /// </summary>
        public double height { get; set; }

        /// <summary>@private
        /// </summary>
        public long bg_color { get; set; }

        /// <summary>@private
        /// </summary>
        public byte[] image_data { get; set; }


    /// <summary>@private
    /// </summary>
    } // end class VisualizeImageLabelsResponse




}  // end namespace kinetica
