/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */

using System.Collections.Generic;



namespace kinetica
{
    /// @cond NO_DOCS
    /// <summary>A set of parameters for <see
    /// cref="Kinetica.visualizeImageClassbreak(IList{string},IList{string},string,string,string,string,IList{IList{string}},string,IList{string},string,IList{string},string,IList{string},string,IList{string},string,IList{string},double,double,double,double,int,int,string,long,IDictionary{string, IList{string}},IDictionary{string, string},IList{int})"
    /// />.
    /// <br />
    /// </summary>
    public class VisualizeImageClassbreakRequest : KineticaData
    {

        /// <summary>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.
        /// A set of string constants for the parameter <see cref="projection"
        /// />.</summary>
        public struct Projection
        {
            public const string EPSG_4326 = "EPSG:4326";
            public const string PLATE_CARREE = "PLATE_CARREE";
            public const string _900913 = "900913";
            public const string EPSG_900913 = "EPSG:900913";
            public const string _102100 = "102100";
            public const string EPSG_102100 = "EPSG:102100";
            public const string _3857 = "3857";
            public const string EPSG_3857 = "EPSG:3857";
            public const string WEB_MERCATOR = "WEB_MERCATOR";
        } // end struct Projection


        /// <summary>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_POINTS">DO_POINTS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SHAPES">DO_SHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_TRACKS">DO_TRACKS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SYMBOLOGY">DO_SYMBOLOGY</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTCOLORS">POINTCOLORS</see>:</term>
        ///         <description>  The default value is 'FF0000'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CB_POINTALPHAS">CB_POINTALPHAS</see>:</term>
        ///         <description>  The default value is '255'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSIZES">POINTSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_X">POINTOFFSET_X</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_Y">POINTOFFSET_Y</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSHAPES">POINTSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DASH">DASH</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PIPE">PIPE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PLUS">PLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUAREWITHPLUS">HOLLOWSQUAREWITHPLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DOT">DOT</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLROTATIONS">SYMBOLROTATIONS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEWIDTHS">SHAPELINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINECOLORS">SHAPELINECOLORS</see>:</term>
        ///         <description>  The default value is 'FFFF00
        /// '.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNS">SHAPELINEPATTERNS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNLEN">SHAPELINEPATTERNLEN</see>:</term>
        ///         <description>  The default value is '32'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPEFILLCOLORS">SHAPEFILLCOLORS</see>:</term>
        ///         <description>  The default value is '-1'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEINTERVALS">HASHLINEINTERVALS</see>:</term>
        ///         <description>  The default value is '20'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINECOLORS">HASHLINECOLORS</see>:</term>
        ///         <description>  The default value is 'The same as line
        /// color.'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEANGLES">HASHLINEANGLES</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINELENS">HASHLINELENS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEWIDTHS">HASHLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINEWIDTHS">TRACKLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINECOLORS">TRACKLINECOLORS</see>:</term>
        ///         <description>  The default value is '00FF00'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSIZES">TRACKMARKERSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERCOLORS">TRACKMARKERCOLORS</see>:</term>
        ///         <description>  The default value is '0000FF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSHAPES">TRACKMARKERSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_ARROW">ORIENTED_ARROW</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_TRIANGLE">ORIENTED_TRIANGLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADCOLORS">TRACKHEADCOLORS</see>:</term>
        ///         <description>  The default value is 'FFFFFF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSIZES">TRACKHEADSIZES</see>:</term>
        ///         <description>  The default value is '10'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSHAPES">TRACKHEADSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see>.</description>
        ///     </item>
        /// </list>
        /// <br />
        /// A set of string constants for the parameter <see
        /// cref="style_options" />.</summary>
        public struct StyleOptions
        {

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</summary>
            public const string DO_POINTS = "do_points";
            public const string TRUE = "true";
            public const string FALSE = "false";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</summary>
            public const string DO_SHAPES = "do_shapes";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</summary>
            public const string DO_TRACKS = "do_tracks";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see>.</summary>
            public const string DO_SYMBOLOGY = "do_symbology";

            /// <summary>  The default value is 'FF0000'.</summary>
            public const string POINTCOLORS = "pointcolors";

            /// <summary>  The default value is '255'.</summary>
            public const string CB_POINTALPHAS = "cb_pointalphas";

            /// <summary>  The default value is '3'.</summary>
            public const string POINTSIZES = "pointsizes";

            /// <summary>  The default value is '0'.</summary>
            public const string POINTOFFSET_X = "pointoffset_x";

            /// <summary>  The default value is '0'.</summary>
            public const string POINTOFFSET_Y = "pointoffset_y";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.DASH">DASH</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.PIPE">PIPE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.PLUS">PLUS</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUAREWITHPLUS">HOLLOWSQUAREWITHPLUS</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.DOT">DOT</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</summary>
            public const string POINTSHAPES = "pointshapes";
            public const string NONE = "none";
            public const string CIRCLE = "circle";
            public const string SQUARE = "square";
            public const string DIAMOND = "diamond";
            public const string HOLLOWCIRCLE = "hollowcircle";
            public const string HOLLOWSQUARE = "hollowsquare";
            public const string HOLLOWDIAMOND = "hollowdiamond";
            public const string SYMBOLCODE = "symbolcode";
            public const string DASH = "dash";
            public const string PIPE = "pipe";
            public const string PLUS = "plus";
            public const string HOLLOWSQUAREWITHPLUS = "hollowsquarewithplus";
            public const string DOT = "dot";

            /// <summary>  The default value is '0'.</summary>
            public const string SYMBOLROTATIONS = "symbolrotations";

            /// <summary>  The default value is '3'.</summary>
            public const string SHAPELINEWIDTHS = "shapelinewidths";

            /// <summary>  The default value is 'FFFF00 '.</summary>
            public const string SHAPELINECOLORS = "shapelinecolors";

            /// <summary>  The default value is '0'.</summary>
            public const string SHAPELINEPATTERNS = "shapelinepatterns";

            /// <summary>  The default value is '32'.</summary>
            public const string SHAPELINEPATTERNLEN = "shapelinepatternlen";

            /// <summary>  The default value is '-1'.</summary>
            public const string SHAPEFILLCOLORS = "shapefillcolors";

            /// <summary>  The default value is '20'.</summary>
            public const string HASHLINEINTERVALS = "hashlineintervals";

            /// <summary>  The default value is 'The same as line
            /// color.'.</summary>
            public const string HASHLINECOLORS = "hashlinecolors";

            /// <summary>  The default value is '0'.</summary>
            public const string HASHLINEANGLES = "hashlineangles";

            /// <summary>  The default value is '0'.</summary>
            public const string HASHLINELENS = "hashlinelens";

            /// <summary>  The default value is '3'.</summary>
            public const string HASHLINEWIDTHS = "hashlinewidths";

            /// <summary>  The default value is '3'.</summary>
            public const string TRACKLINEWIDTHS = "tracklinewidths";

            /// <summary>  The default value is '00FF00'.</summary>
            public const string TRACKLINECOLORS = "tracklinecolors";

            /// <summary>  The default value is '3'.</summary>
            public const string TRACKMARKERSIZES = "trackmarkersizes";

            /// <summary>  The default value is '0000FF'.</summary>
            public const string TRACKMARKERCOLORS = "trackmarkercolors";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_ARROW">ORIENTED_ARROW</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_TRIANGLE">ORIENTED_TRIANGLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</summary>
            public const string TRACKMARKERSHAPES = "trackmarkershapes";
            public const string ORIENTED_ARROW = "oriented_arrow";
            public const string ORIENTED_TRIANGLE = "oriented_triangle";

            /// <summary>  The default value is 'FFFFFF'.</summary>
            public const string TRACKHEADCOLORS = "trackheadcolors";

            /// <summary>  The default value is '10'.</summary>
            public const string TRACKHEADSIZES = "trackheadsizes";

            /// <summary>
            /// Supported values:
            /// <list type="bullet">
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
            ///     </item>
            ///     <item>
            ///         <term><see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
            ///     </item>
            /// </list>
            /// The default value is <see
            /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see>.</summary>
            public const string TRACKHEADSHAPES = "trackheadshapes";
        } // end struct StyleOptions


        /// <summary>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ID_COLUMN_NAME">TRACK_ID_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ORDER_COLUMN_NAME">TRACK_ORDER_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        /// </list>
        /// <br />
        /// A set of string constants for the parameter <see cref="options"
        /// />.</summary>
        public struct Options
        {
            public const string TRACK_ID_COLUMN_NAME = "track_id_column_name";
            public const string TRACK_ORDER_COLUMN_NAME = "track_order_column_name";
        } // end struct Options

        public IList<string> table_names { get; set; } = new List<string>();
        public IList<string> world_table_names { get; set; } = new List<string>();
        public string x_column_name { get; set; }
        public string y_column_name { get; set; }
        public string symbol_column_name { get; set; }
        public string geometry_column_name { get; set; }
        public IList<IList<string>> track_ids { get; set; } = new List<IList<string>>();
        public string cb_attr { get; set; }
        public IList<string> cb_vals { get; set; } = new List<string>();
        public string cb_pointcolor_attr { get; set; }
        public IList<string> cb_pointcolor_vals { get; set; } = new List<string>();
        public string cb_pointalpha_attr { get; set; }
        public IList<string> cb_pointalpha_vals { get; set; } = new List<string>();
        public string cb_pointsize_attr { get; set; }
        public IList<string> cb_pointsize_vals { get; set; } = new List<string>();
        public string cb_pointshape_attr { get; set; }
        public IList<string> cb_pointshape_vals { get; set; } = new List<string>();
        public double min_x { get; set; }
        public double max_x { get; set; }
        public double min_y { get; set; }
        public double max_y { get; set; }
        public int width { get; set; }
        public int height { get; set; }

        /// <summary>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.</summary>
        public string projection { get; set; } = Projection.PLATE_CARREE;
        public long bg_color { get; set; }

        /// <summary>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_POINTS">DO_POINTS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SHAPES">DO_SHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_TRACKS">DO_TRACKS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SYMBOLOGY">DO_SYMBOLOGY</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTCOLORS">POINTCOLORS</see>:</term>
        ///         <description>  The default value is 'FF0000'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CB_POINTALPHAS">CB_POINTALPHAS</see>:</term>
        ///         <description>  The default value is '255'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSIZES">POINTSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_X">POINTOFFSET_X</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_Y">POINTOFFSET_Y</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSHAPES">POINTSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DASH">DASH</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PIPE">PIPE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PLUS">PLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUAREWITHPLUS">HOLLOWSQUAREWITHPLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DOT">DOT</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLROTATIONS">SYMBOLROTATIONS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEWIDTHS">SHAPELINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINECOLORS">SHAPELINECOLORS</see>:</term>
        ///         <description>  The default value is 'FFFF00
        /// '.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNS">SHAPELINEPATTERNS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNLEN">SHAPELINEPATTERNLEN</see>:</term>
        ///         <description>  The default value is '32'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPEFILLCOLORS">SHAPEFILLCOLORS</see>:</term>
        ///         <description>  The default value is '-1'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEINTERVALS">HASHLINEINTERVALS</see>:</term>
        ///         <description>  The default value is '20'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINECOLORS">HASHLINECOLORS</see>:</term>
        ///         <description>  The default value is 'The same as line
        /// color.'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEANGLES">HASHLINEANGLES</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINELENS">HASHLINELENS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEWIDTHS">HASHLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINEWIDTHS">TRACKLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINECOLORS">TRACKLINECOLORS</see>:</term>
        ///         <description>  The default value is '00FF00'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSIZES">TRACKMARKERSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERCOLORS">TRACKMARKERCOLORS</see>:</term>
        ///         <description>  The default value is '0000FF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSHAPES">TRACKMARKERSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_ARROW">ORIENTED_ARROW</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_TRIANGLE">ORIENTED_TRIANGLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADCOLORS">TRACKHEADCOLORS</see>:</term>
        ///         <description>  The default value is 'FFFFFF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSIZES">TRACKHEADSIZES</see>:</term>
        ///         <description>  The default value is '10'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSHAPES">TRACKHEADSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see>.</description>
        ///     </item>
        /// </list>
        /// </summary>
        public IDictionary<string, IList<string>> style_options { get; set; } = new Dictionary<string, IList<string>>();

        /// <summary>
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ID_COLUMN_NAME">TRACK_ID_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ORDER_COLUMN_NAME">TRACK_ORDER_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        /// </list>
        /// </summary>
        public IDictionary<string, string> options { get; set; } = new Dictionary<string, string>();
        public IList<int> cb_transparency_vec { get; set; } = new List<int>();


        /// <summary>Constructs a VisualizeImageClassbreakRequest object with
        /// default parameters.</summary>
        public VisualizeImageClassbreakRequest() { }

        /// <summary>Constructs a VisualizeImageClassbreakRequest object with
        /// the specified parameters.</summary>
        /// 
        /// <param name="table_names"></param>
        /// <param name="world_table_names"></param>
        /// <param name="x_column_name"></param>
        /// <param name="y_column_name"></param>
        /// <param name="symbol_column_name"></param>
        /// <param name="geometry_column_name"></param>
        /// <param name="track_ids"></param>
        /// <param name="cb_attr"></param>
        /// <param name="cb_vals"></param>
        /// <param name="cb_pointcolor_attr"></param>
        /// <param name="cb_pointcolor_vals"></param>
        /// <param name="cb_pointalpha_attr"></param>
        /// <param name="cb_pointalpha_vals"></param>
        /// <param name="cb_pointsize_attr"></param>
        /// <param name="cb_pointsize_vals"></param>
        /// <param name="cb_pointshape_attr"></param>
        /// <param name="cb_pointshape_vals"></param>
        /// <param name="min_x"></param>
        /// <param name="max_x"></param>
        /// <param name="min_y"></param>
        /// <param name="max_y"></param>
        /// <param name="width"></param>
        /// <param name="height"></param>
        /// <param name="projection">
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_4326">EPSG_4326</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._900913">_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_900913">EPSG_900913</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._102100">_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_102100">EPSG_102100</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection._3857">_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.EPSG_3857">EPSG_3857</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Projection.WEB_MERCATOR">WEB_MERCATOR</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.Projection.PLATE_CARREE">PLATE_CARREE</see>.</param>
        /// <param name="bg_color"></param>
        /// <param name="style_options">
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_POINTS">DO_POINTS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SHAPES">DO_SHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_TRACKS">DO_TRACKS</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DO_SYMBOLOGY">DO_SYMBOLOGY</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRUE">TRUE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.FALSE">FALSE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTCOLORS">POINTCOLORS</see>:</term>
        ///         <description>  The default value is 'FF0000'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CB_POINTALPHAS">CB_POINTALPHAS</see>:</term>
        ///         <description>  The default value is '255'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSIZES">POINTSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_X">POINTOFFSET_X</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTOFFSET_Y">POINTOFFSET_Y</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.POINTSHAPES">POINTSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DASH">DASH</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PIPE">PIPE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.PLUS">PLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUAREWITHPLUS">HOLLOWSQUAREWITHPLUS</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DOT">DOT</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLROTATIONS">SYMBOLROTATIONS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEWIDTHS">SHAPELINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINECOLORS">SHAPELINECOLORS</see>:</term>
        ///         <description>  The default value is 'FFFF00
        /// '.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNS">SHAPELINEPATTERNS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPELINEPATTERNLEN">SHAPELINEPATTERNLEN</see>:</term>
        ///         <description>  The default value is '32'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SHAPEFILLCOLORS">SHAPEFILLCOLORS</see>:</term>
        ///         <description>  The default value is '-1'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEINTERVALS">HASHLINEINTERVALS</see>:</term>
        ///         <description>  The default value is '20'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINECOLORS">HASHLINECOLORS</see>:</term>
        ///         <description>  The default value is 'The same as line
        /// color.'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEANGLES">HASHLINEANGLES</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINELENS">HASHLINELENS</see>:</term>
        ///         <description>  The default value is '0'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HASHLINEWIDTHS">HASHLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINEWIDTHS">TRACKLINEWIDTHS</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKLINECOLORS">TRACKLINECOLORS</see>:</term>
        ///         <description>  The default value is '00FF00'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSIZES">TRACKMARKERSIZES</see>:</term>
        ///         <description>  The default value is '3'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERCOLORS">TRACKMARKERCOLORS</see>:</term>
        ///         <description>  The default value is '0000FF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKMARKERSHAPES">TRACKMARKERSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_ARROW">ORIENTED_ARROW</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.ORIENTED_TRIANGLE">ORIENTED_TRIANGLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see>.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADCOLORS">TRACKHEADCOLORS</see>:</term>
        ///         <description>  The default value is 'FFFFFF'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSIZES">TRACKHEADSIZES</see>:</term>
        ///         <description>  The default value is '10'.</description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.TRACKHEADSHAPES">TRACKHEADSHAPES</see>:</term>
        ///         <description>
        /// Supported values:
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.NONE">NONE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SQUARE">SQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.DIAMOND">DIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWCIRCLE">HOLLOWCIRCLE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWSQUARE">HOLLOWSQUARE</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.HOLLOWDIAMOND">HOLLOWDIAMOND</see></term>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.SYMBOLCODE">SYMBOLCODE</see></term>
        ///     </item>
        /// </list>
        /// The default value is <see
        /// cref="VisualizeImageClassbreakRequest.StyleOptions.CIRCLE">CIRCLE</see>.</description>
        ///     </item>
        /// </list>
        /// </param>
        /// <param name="options">
        /// <list type="bullet">
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ID_COLUMN_NAME">TRACK_ID_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        ///     <item>
        ///         <term><see
        /// cref="VisualizeImageClassbreakRequest.Options.TRACK_ORDER_COLUMN_NAME">TRACK_ORDER_COLUMN_NAME</see>:</term>
        ///         <description></description>
        ///     </item>
        /// </list>
        /// </param>
        /// <param name="cb_transparency_vec"></param>
        /// 
        public VisualizeImageClassbreakRequest( IList<string> table_names,
                                                IList<string> world_table_names,
                                                string x_column_name,
                                                string y_column_name,
                                                string symbol_column_name,
                                                string geometry_column_name,
                                                IList<IList<string>> track_ids,
                                                string cb_attr,
                                                IList<string> cb_vals,
                                                string cb_pointcolor_attr,
                                                IList<string> cb_pointcolor_vals,
                                                string cb_pointalpha_attr,
                                                IList<string> cb_pointalpha_vals,
                                                string cb_pointsize_attr,
                                                IList<string> cb_pointsize_vals,
                                                string cb_pointshape_attr,
                                                IList<string> cb_pointshape_vals,
                                                double min_x,
                                                double max_x,
                                                double min_y,
                                                double max_y,
                                                int width,
                                                int height,
                                                string projection,
                                                long bg_color,
                                                IDictionary<string, IList<string>> style_options,
                                                IDictionary<string, string> options,
                                                IList<int> cb_transparency_vec)
        {
            this.table_names = table_names ?? new List<string>();
            this.world_table_names = world_table_names ?? new List<string>();
            this.x_column_name = x_column_name ?? "";
            this.y_column_name = y_column_name ?? "";
            this.symbol_column_name = symbol_column_name ?? "";
            this.geometry_column_name = geometry_column_name ?? "";
            this.track_ids = track_ids ?? new List<IList<string>>();
            this.cb_attr = cb_attr ?? "";
            this.cb_vals = cb_vals ?? new List<string>();
            this.cb_pointcolor_attr = cb_pointcolor_attr ?? "";
            this.cb_pointcolor_vals = cb_pointcolor_vals ?? new List<string>();
            this.cb_pointalpha_attr = cb_pointalpha_attr ?? "";
            this.cb_pointalpha_vals = cb_pointalpha_vals ?? new List<string>();
            this.cb_pointsize_attr = cb_pointsize_attr ?? "";
            this.cb_pointsize_vals = cb_pointsize_vals ?? new List<string>();
            this.cb_pointshape_attr = cb_pointshape_attr ?? "";
            this.cb_pointshape_vals = cb_pointshape_vals ?? new List<string>();
            this.min_x = min_x;
            this.max_x = max_x;
            this.min_y = min_y;
            this.max_y = max_y;
            this.width = width;
            this.height = height;
            this.projection = projection ?? Projection.PLATE_CARREE;
            this.bg_color = bg_color;
            this.style_options = style_options ?? new Dictionary<string, IList<string>>();
            this.options = options ?? new Dictionary<string, string>();
            this.cb_transparency_vec = cb_transparency_vec ?? new List<int>();
        } // end constructor

    } // end class VisualizeImageClassbreakRequest
    /// @endcond



    /// @cond NO_DOCS
    /// <summary>A set of results returned by <see
    /// cref="Kinetica.visualizeImageClassbreak(IList{string},IList{string},string,string,string,string,IList{IList{string}},string,IList{string},string,IList{string},string,IList{string},string,IList{string},string,IList{string},double,double,double,double,int,int,string,long,IDictionary{string, IList{string}},IDictionary{string, string},IList{int})"
    /// />.</summary>
    public class VisualizeImageClassbreakResponse : KineticaData
    {
        public double width { get; set; }
        public double height { get; set; }
        public long bg_color { get; set; }
        public byte[] image_data { get; set; }
        public IDictionary<string, string> info { get; set; } = new Dictionary<string, string>();

    } // end class VisualizeImageClassbreakResponse
    /// @endcond





}  // end namespace kinetica
