<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Project-specific settings that override Directory.Build.props -->
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kinetica\Kinetica.csproj" />
  </ItemGroup>

</Project>
